### ISSUE TITLE
I can get a token, but not a notification

### ISSUE THREAD

**Issue by williamrodz** [afrihost/firebasePushTest#2]
Great work on this!

I am running example app code and am able to get a message token and permissions from my device. I am trying to send a test notification from Firebase and am using my device's token. However, nothing happens upon triggering a test notification. Any tips?

**Comment by iarmankhan** [comment]
Same issue here but it did receive notification when I send it from there (instead of test notification)
![image](https://user-images.githubusercontent.com/40450695/77883660-31331380-7281-11ea-9778-c99b9f239f10.png)
Using this!

Any updates on this?

**Comment by sacheen** [comment]
Hi, Some tips.
Make sure you using your firebase config in your application.
Make sure you running it on a physical device if testing on iOS and make sure you requested and accepted permission.
Android sometimes you have to un-install the app the re-install on the simulator to get the notification. 
Keep in mind notifications only "Display" when the app is in background or not running.
